<a href="https://colab.research.google.com/github/SrinidhiMokidi/GenAI/blob/main/GenAI_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Sample data from the table
y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

# Calculate error metrics from scratch
def mean_squared_error_scratch(y_actual, y_pred):
    """Calculates Mean Squared Error."""
    mse = np.mean((y_actual - y_pred)**2)
    return mse

def mean_absolute_error_scratch(y_actual, y_pred):
    """Calculates Mean Absolute Error."""
    mae = np.mean(np.abs(y_actual - y_pred))
    return mae

# Calculate error metrics using scikit-learn library
mse_sklearn = mean_squared_error(y_actual, y_pred)
mae_sklearn = mean_absolute_error(y_actual, y_pred)
r2_sklearn = r2_score(y_actual, y_pred)

# Print results
print("Mean Squared Error (Scratch):", mean_squared_error_scratch(y_actual, y_pred))
print("Mean Squared Error (Scikit-learn):", mse_sklearn)

print("Mean Absolute Error (Scratch):", mean_absolute_error_scratch(y_actual, y_pred))
print("Mean Absolute Error (Scikit-learn):", mae_sklearn)

print("R-squared (Scikit-learn):", r2_sklearn)

Mean Squared Error (Scratch): 0.24600000000000147
Mean Squared Error (Scikit-learn): 0.24600000000000147
Mean Absolute Error (Scratch): 0.4600000000000016
Mean Absolute Error (Scikit-learn): 0.4600000000000016
R-squared (Scikit-learn): 0.99877


In [2]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

Y_actual = np.array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
Y_pred = np.array([0, 1, 0, 0, 0, 0, 1, 2, 1, 2, 2, 2])

def confusion_matrix_from_scratch(y_true, y_pred):
    classes = np.unique(y_true)
    matrix = np.zeros((len(classes), len(classes)), dtype=int)

    for true, pred in zip(y_true, y_pred):
        matrix[true, pred] += 1

    return matrix

def calculate_precision_recall_f1(matrix):
    tp = np.diag(matrix)
    fp = np.sum(matrix, axis=0) - tp
    fn = np.sum(matrix, axis=1) - tp
    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    f1 = 2 * (precision * recall) / (precision + recall)

    return precision, recall, f1

cm = confusion_matrix_from_scratch(Y_actual, Y_pred)
print(f"Confusion Matrix (from scratch):\n{cm}")

precision, recall, f1 = calculate_precision_recall_f1(cm)
print("\nPrecision, Recall, F1-Score (from scratch):")
for i in range(len(precision)):
    print(f"Class {i}: Precision = {precision[i]}, Recall = {recall[i]}, F1-Score = {f1[i]}")


accuracy = accuracy_score(Y_actual, Y_pred)
precision_lib = precision_score(Y_actual, Y_pred, average=None)
recall_lib = recall_score(Y_actual, Y_pred, average=None)
f1_lib = f1_score(Y_actual, Y_pred, average=None)
confusion_matrix_lib = confusion_matrix(Y_actual, Y_pred)




Confusion Matrix (from scratch):
[[2 1 1]
 [1 1 2]
 [2 1 1]]

Precision, Recall, F1-Score (from scratch):
Class 0: Precision = 0.4, Recall = 0.5, F1-Score = 0.4444444444444445
Class 1: Precision = 0.3333333333333333, Recall = 0.25, F1-Score = 0.28571428571428575
Class 2: Precision = 0.25, Recall = 0.25, F1-Score = 0.25
